service: express-vpn-updater
configValidationMode: error

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: go1.x
  lambdaHashingVersion: 20201221

  iam:
    role: arn:aws:iam::081940731328:role/lambda-s3

plugins:
  - serverless-offline

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  hello:
    handler: bin/healthcheck
    events:
      - http:
          path: /healthcheck
          method: get
          cors: true

  scrape:
    handler: bin/scrape-latest
    events:
      - http:
          path: /latest
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                redirect: false
