service: express-vpn-updater
configValidationMode: error

# Configure a different S3 bucket name for prod and dev
custom:
  vars: ${file(vars.yml):${opt:stage, self:provider.stage}, file(vars.yml):dev}

plugins:
  - serverless-offline

package:
  patterns:
    - "!./**"
    - ./bin/**

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: go1.x
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
            - "s3:ListObjectsV2"
            - "s3:PutObject"
            - "s3:GetObject"
            - "s3:DeleteObject"
          Resource: "arn:aws:s3:::*express-vpn-updater*"

resources:
  Description: .deb package cache
  Resources:
    S3Bucket:
      Type: "AWS::S3::Bucket"
      DeletionPolicy: Delete
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.vars.BUCKET_NAME}

functions:
  healthcheck:
    handler: bin/healthcheck.GET
    events:
      - http:
          path: /healthcheck
          method: get
          cors: true

  latest:
    handler: bin/latest.GET
    events:
      - http:
          path: /latest
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                redirect: false
                fresh: false
