name: "[BACKEND] Go Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Go Deploy
    runs-on: ubuntu-latest
    env:
      go-version: "1.16"
      node-version: "16"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - run: |
          echo "Deploying"
