name: "[BACKEND] Go Build n' Test"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        required: false
        description: "Test scenario tags"

jobs:
  test:
    name: "Build n' Test"
    runs-on: ubuntu-latest
    env:
      go-version: "^1.16"
      node-version: "16"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Use Go ${{ env.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - run: |
          ####>>>==- 👍👍👍👌👌😂 SCRIPT 😂👌👌👍👍👍 -==<<<####
          cd server
          yarn install --dev
          yarn test
          yarn build
